# Generated by Django 5.2.14 on 2026-05-15 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temp_alta', 'Temperatura Alta'), ('vibracao', 'Vibracao'), ('pressao', 'Pressao'), ('outro', 'Outro')], default='temp_alta', max_length=20)),
                ('detected_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limit_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criticality', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('viewed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='machines.machine')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensorreading')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
