# Generated by Django 5.2.12 on 2026-04-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ANOMALY', 'Anomalia'), ('THRESHOLD', 'Limite Ultrapassado'), ('PREDICTIVE', 'Preditivo'), ('MANUAL', 'Manual')], default='THRESHOLD', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Baixo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('ACKNOWLEDGED', 'Reconhecido'), ('RESOLVED', 'Resolvido')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
