# Generated by Django 5.2.12 on 2026-04-04 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ANOMALY', 'Anomalia'), ('THRESHOLD', 'Limite Ultrapassado'), ('PREDICTIVE', 'Preditivo'), ('MANUAL', 'Manual')], default='THRESHOLD', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Baixo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('ACKNOWLEDGED', 'Reconhecido'), ('RESOLVED', 'Resolvido')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='machines.machine')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensorreading')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'), models.Index(fields=['risk_level', '-created_at'], name='alerts_aler_risk_le_36b506_idx'), models.Index(fields=['machine', '-created_at'], name='alerts_aler_machine_cd30a1_idx')],
            },
        ),
    ]
