# Generated by Django 5.2.12 on 2026-04-15 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('machines', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='alert',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensorreading'),
        ),
    ]
