# Generated by Django 5.2.12 on 2026-04-15 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='sensors.sensor'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='alerts_aler_status_e70a14_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['risk_level', '-created_at'], name='alerts_aler_risk_le_36b506_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['machine', '-created_at'], name='alerts_aler_machine_cd30a1_idx'),
        ),
    ]
