# Generated by Django 5.2.12 on 2026-04-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='machine',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='machines', to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
