# Generated by Django 5.2.12 on 2026-05-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='preventive_maintenance_interval',
            field=models.IntegerField(blank=True, help_text='Intervalo em dias para gerar OS preventiva automática', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='telemetry_interval',
            field=models.IntegerField(default=0, help_text='Intervalo em minutos para armazenar leituras (0 = contínuo)'),
        ),
    ]
