# Generated by Django 5.2.12 on 2026-04-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalo em dias para manutencao preventiva', null=True),
        ),
    ]
