# Generated by Django 5.2.14 on 2026-05-15 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('next_maintenance_deadline', models.IntegerField(blank=True, help_text='Prazo para a proxima manutencao (em dias)', null=True)),
                ('performed_date', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='machines.machine')),
            ],
            options={
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('emergencial', 'Emergencial'), ('preditiva', 'Preditiva'), ('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=20)),
                ('production_line', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=20)),
                ('observation', models.TextField(blank=True, null=True)),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='alerts.alert')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='machines.machine')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_orders', to=settings.AUTH_USER_MODEL)),
                ('previous_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_orders', to='work_orders.maintenance')),
            ],
            options={
                'ordering': ['-opening_date'],
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='work_orders.workorder'),
        ),
    ]
