# Generated by Django 5.2.12 on 2026-05-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='work_orders.workorderstatus'),
        ),
    ]
