# Generated by Django 5.2.12 on 2026-05-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_workorderstatus_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='production_line',
            field=models.CharField(blank=True, default='Não informada', max_length=100, null=True),
        ),
    ]
