# Generated by Django 5.2.12 on 2026-05-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_workorder_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='temperature',
        ),
    ]
