# Generated by Django 5.2.12 on 2026-04-15 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sensor_type', models.CharField(choices=[('TEMPERATURE', 'Temperatura'), ('VIBRATION', 'Vibracao'), ('PRESSURE', 'Pressao'), ('HUMIDITY', 'Umidade'), ('CURRENT', 'Corrente Eletrica'), ('VOLTAGE', 'Tensao'), ('RPM', 'Rotacao (RPM)'), ('OTHER', 'Outro')], default='OTHER', max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('min_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='machines.machine')),
            ],
            options={
                'ordering': ['machine', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('timestamp', models.DateTimeField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='sensors_sen_sensor__d03b31_idx'), models.Index(fields=['is_anomaly', '-timestamp'], name='sensors_sen_is_anom_1e8f89_idx')],
            },
        ),
    ]
