# Generated by Django 5.2.12 on 2026-05-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='min_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
