# Generated by Django 5.2.12 on 2026-05-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('tecnico', 'Técnico'), ('operador', 'Operador'), ('visualizador', 'Visualizador')], default='visualizador', max_length=20),
        ),
    ]
