# Generated by Django 5.2.12 on 2026-04-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_role',
            field=models.CharField(choices=[('MANAGER', 'Gerente'), ('ANALYST', 'Analista'), ('INTERN', 'Estagiario'), ('DIRECTOR', 'Diretor'), ('TECHNICIAN', 'Tecnico'), ('OPERATOR', 'Operador')], default='OPERATOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TECHNICIAN', 'Tecnico'), ('MANAGER', 'Gestor')], default='TECHNICIAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
